namespace:
  name: prod

service:
  port: 7111
  targetPort: 8111
  protocol: TCP
  type: ClusterIP

replicaCount: 5

image:
  repository: charledo/techtrends
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m

containerPort: 8111

livenessProbe:
  path: /healthz
  port: 7111

readinessProbe:
  path: /healthz
  port: 7111
