namespace:
  name: staging

replicaCount: 3

image:
  repository: charledo/techtrends
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 5111
  targetPort: 6111
  protocol: TCP
  type: ClusterIP

resources:
  requests:
    memory: 90Mi
    cpu: 300m
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 6111

livenessProbe:
  path: /healthz
  port: 6111

readinessProbe:
  path: /healthz
  port: 6111
